project:
  type: website

website:
  title: "Introducing Joe Rickert"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: Work History
      - href: Publications.qmd
        text: Publications
      - href: Egypt.qmd
        text: Egypt
      
  
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

